[workspace]
authors = ["mattbocc <matthew.boccalon@live.ca>"]
channels = ["conda-forge"]
name = "annotationdb-seeding"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.5,<3.14"
sqlalchemy = ">=2.0.42,<3"
python-dotenv = ">=1.1.1,<2"
pymysql = ">=1.1.1,<2"
pandas = ">=2.3.2,<3"
requests = ">=2.32.5,<3"

[pypi-dependencies]
chembl-webresource-client = ">=0.10.9, <0.11"
